name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract ZIP and Setup Configs
        run: |
          for f in *.zip; do [ -f "$f" ] && unzip -o "$f"; done || true
          touch .env
          mkdir -p ~/.android
          keytool -genkey -v -keystore ./debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          cp ./debug.keystore ~/.android/debug.keystore || true

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11.1

      - name: Generate Wrapper & Build APK
        run: |
          gradle wrapper
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --no-daemon -x test

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SoundSync-Debug-APK
          path: "**/build/outputs/apk/debug/*.apk"
